# Peforms the setup requried to create a new release
name: Setup For Release

# The list of tasks to perform
  #Sets up all the required tools required to build the libraries and applications
runs:
    using: "composite"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          check-latest: true
      - name: Setup Tools
        shell: bash
        run: |
          echo "----Python Version----"
          python --version
          echo "----------------------"
          
          # Installs the python package manager
          python -m pip install --upgrade pip
          
          # Dependencies required for building the packages/libraries
          pip install setuptools
          pip install wheel
       
          
