#The client connection information
[Server]
Port = 25003

[Propulsion]
#0 = TopRight Purple  
#1 = TopLeft Green
#2 = FrontRight Orange
#3 = FrontLeft Lime Green
#4 = BackRight blue
#5 = BackLeft yellow
FrontLeftThrusterPin = 22
FrontRightThrusterPin = 27
BackLeftThrusterPin = 24
BackRightThrusterPin = 17
TopLeftThrusterPin = 23
TopRightThrusterPin = 18

[Illumination]
SubseaLightPin = 5

#Parameters for testing the code
[Testing]
#Used for testing without a controller
FakeHardware = false
