#The client connection information
[Server]
Port = 25003

[Propulsion]
#0 Front Top   Yellow
#1 Back Top    Yellow Blue
#2 Front Left  Yellow Red
#3 Back Left   Red
#4 Front Right Blue Red
#5 Back Right  Blue
TopFrontThrusterPin = 23
TopBackThrusterPin = 18
FrontLeftThrusterPin = 22
BackLeftThrusterPin = 27
FrontRightThrusterPin = 24
BackRightThrusterPin = 17

[Illumination]
SubseaLightPin = 25

#Parameters for testing the code
[Testing]
#Used for testing without a controller
FakeHardware = false
