# Creates a new release when 
name: Create Release

# Controls when the workflow will run
on:
  # Triggers the release creation when changes are pushed onto the master branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# The list of tasks to perform
jobs:
  #Sets up all the required tools and build the packages and applications
  build:
    # Perform all of the setup an a machine running Ubuntu/Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          check-latest: true
      - name: Setup commands
          run python version
          run python -m pip install --upgrade pip
          pip install setuptools
          pip install wheel
          
        # Builds the messaging library
      - name: Build Messaging
          run cd "Common/Messaging"
          run python setup.py bdist_wheel
          run cd dist
          run ls
          
  # Builds the custom packages
  build-dependences:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    #steps:
        
      # TODO

          
  # Creates the executables for the ROV and Client Programs
  build-applications:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      
       # TODO
      
  # Creates the actual release
  create-release:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      
       # TODO
      
